devel_devel:
    resource: "@DevelDevelBundle/Resources/config/routing.yml"
    prefix:   /

blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
