Blogger\BlogBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        author:
            type: string
            scale: 0
            length: 100
            unique: false
            nullable: false
            precision: 0
        blog:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        image:
            type: string
            scale: 0
            length: 20
            unique: false
            nullable: false
            precision: 0
        tags:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        created:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        updated:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks:
        preUpdate:
            - setUpdatedValue
